### ISSUE TITLE
Technical design

### ISSUE THREAD

**Issue by ghost** [ravimik/bwa-u4-feature-request#3]
> Within the return statement  of Spotify.search we’ll add the key:value pair of “preview_url: track.preview_url”.

Great! Nicely job researching the Spotify API to implement this feature as simply as possible! 👍 

> Write conditional statement to ensure track.preview_url exists
{this.props.track.preview_url ? : }
Within the render method’s return statement of Track.js, add `<a href={this.props.track.preview_url} target=”_blank”>{this.props.track.name} Sample</a>`

Interesting, so this feature would require the user to leave the app for every track that they want to preview... Could this be improved so that the preview is played on an audio player on the same page? 

It could be easily become the case that this feature leaves the user with a large amount of extra tabs, and it's not uncommon to close useful tabs when trying to clear the others.

**Comment by ravimik** [comment]
Very true on closing tabs, happens to me a lot when I have 80 tabs across 4 windows. I'm pretty sure there's a player endpoint and I plan to explore that next.
