### ISSUE TITLE
Caveats

### ISSUE THREAD

**Issue by ghost** [ravimik/bwa-u4-feature-request#4]
> An ideal solution will be implementing a player function directly in the TrackList  on the page, but that goes beyond the scope of “Get those previews up right now” which we were ordered to do. 

...What? Who ordered you?

Even if it's not feasible to implement the optimal solution at the moment, an initial proposal should still elaborate on _why_ it's not feasible and this involves actually designing that solution (even if not implementing in favor of a less optimal solution). 

Telling a manager or employer, "I didn't think of how I'd implement the ideal solution because you wanted it done fast" does not leave a great impression. How would you know the ideal solution couldn't be done fast without trying to design it first? What are you basing this on?

**Comment by ravimik** [comment]
I was being a bit cheeky, and was rushing to get this finished before I go on a work trip and then won't have more time to work on it.
