### ISSUE TITLE
Summary

### ISSUE THREAD

**Issue by ghost** [ravimik/bwa-u4-feature-request#5]
Satisfactory

Great idea and your technical design seems sound, though it comes with its own potential drawbacks in practice. 

You should try to implement this feature and then see if you can get the more optimal solution working!

**Comment by ravimik** [comment]
Thanks Steve! I actually did implement it while I was writing the document and it led me to all of the CSS issues, the if statement, and some of what I wrote in the caveat. Really shows the power of building and iterating over just thinking/writing.
